2020-10-17 11:06:59,284	INFO services.py:1164 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
E1017 11:20:36.741364 43039 43198 core_worker.cc:411] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=__main__, class_name=, function_name=run_experiment_p, function_hash=abd553d579a61161d91ccd1d3e6888e20397b2b8}, task_id=c61c90f84b215448ffffffff01000000, task_name=run_experiment_p(), job_id=01000000, num_args=2, num_returns=1
E1017 11:20:40.891587 43039 43198 core_worker.cc:411] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=__main__, class_name=, function_name=run_experiment_p, function_hash=abd553d579a61161d91ccd1d3e6888e20397b2b8}, task_id=11d7f983e14011f4ffffffff01000000, task_name=run_experiment_p(), job_id=01000000, num_args=2, num_returns=1
E1017 11:20:41.500313 43039 43198 core_worker.cc:411] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=__main__, class_name=, function_name=run_experiment_p, function_hash=abd553d579a61161d91ccd1d3e6888e20397b2b8}, task_id=7d269126652173d0ffffffff01000000, task_name=run_experiment_p(), job_id=01000000, num_args=2, num_returns=1
E1017 11:21:21.097751 43039 43198 core_worker.cc:411] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=__main__, class_name=, function_name=run_experiment_p, function_hash=abd553d579a61161d91ccd1d3e6888e20397b2b8}, task_id=82be70daa7562412ffffffff01000000, task_name=run_experiment_p(), job_id=01000000, num_args=2, num_returns=1
E1017 11:23:18.051090 43039 43198 direct_task_transport.cc:331] The worker failed to receive a response from the local raylet. This is most likely because the local raylet has crahsed.
F1017 11:23:18.312930 43039 43198 direct_task_transport.cc:334] IOError: 14: Socket closed
*** Check failure stack trace: ***
[2m[36m(pid=43136)[0m E1017 11:23:18.886458 43136 44041 core_worker.cc:693] Raylet failed. Shutting down.
2020-10-17 11:21:14,801	WARNING worker.py:1072 -- The node with node id 6700797443e1cb2a6cf0d60feea94e54a69721f9 has been marked dead because the detector has missed too many heartbeats from it.
2020-10-17 11:24:25,496	WARNING worker.py:1072 -- A worker died or was killed while executing task c61c90f84b215448ffffffff01000000.
2020-10-17 11:24:25,497	WARNING worker.py:1072 -- A worker died or was killed while executing task 11d7f983e14011f4ffffffff01000000.
2020-10-17 11:24:25,497	WARNING worker.py:1072 -- A worker died or was killed while executing task 7d269126652173d0ffffffff01000000.
2020-10-17 11:24:25,497	WARNING worker.py:1072 -- A worker died or was killed while executing task 82be70daa7562412ffffffff01000000.
    @     0x2aaae28646ed  google::LogMessage::Fail()
    @     0x2aaae286584c  google::LogMessage::SendToLog()
    @     0x2aaae28643c9  google::LogMessage::Flush()
    @     0x2aaae28645e1  google::LogMessage::~LogMessage()
    @     0x2aaae281b789  ray::RayLog::~RayLog()
    @     0x2aaae24faffc  _ZZN3ray29CoreWorkerDirectTaskSubmitter24RequestNewWorkerIfNeededERKSt5tupleIIiSt6vectorINS_8ObjectIDESaIS3_EENS_7ActorIDEEEPKNS_3rpc7AddressEENKUlRKNS_6StatusERKNSA_23RequestWorkerLeaseReplyEE_clESG_SJ_
    @     0x2aaae2539965  ray::rpc::ClientCallImpl<>::OnReplyReceived()
    @     0x2aaae2499c30  _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
    @     0x2aaae28c5c3f  boost::asio::detail::scheduler::do_run_one()
    @     0x2aaae28c6a01  boost::asio::detail::scheduler::run()
    @     0x2aaae28c7952  boost::asio::io_context::run()
    @     0x2aaae247b310  ray::CoreWorker::RunIOService()
    @     0x2aaac2814421  execute_native_thread_routine_compat
    @     0x2aaaaacd6ea5  start_thread
    @     0x2aaaaafe98dd  __clone
/cm/local/apps/slurm/var/spool/job8474994/slurm_script: line 20: 43039 Aborted                 /home/akanji/miniconda3/envs/seldnian-pre/bin/python experiment_s_p.py "$@"
